"""Data schemas and contracts for the Multi-Agent Research System."""

from typing import List, Optional
from pydantic import BaseModel, Field


class Source(BaseModel):
    """Web source retrieved during research."""

    url: str = Field(description="Direct URL of the source page")
    title: str = Field(default="", description="Title of the webpage or article")
    snippet: str = Field(default="", description="Search snippet or summary from search engine")


class ResearchPlan(BaseModel):
    """Structured plan and source list generated by the research phase."""

    query: str = Field(description="Original user query")
    search_queries: List[str] = Field(
        default_factory=list,
        description="Targeted search queries generated to cover the topic comprehensively",
    )
    sources: List[Source] = Field(
        default_factory=list,
        description="Deduplicated list of web sources gathered for synthesis",
    )


class Extract(BaseModel):
    """Cleaned webpage extract retrieved by the parallel reader."""

    url: str = Field(description="URL of the page")
    title: str = Field(default="", description="Title extracted from the HTML")
    content: str = Field(description="Cleaned main body text extracted from HTML")
    error: Optional[str] = Field(
        default=None,
        description="Error message if fetching or parsing failed",
    )


class Section(BaseModel):
    """Section within the research report."""

    heading: str = Field(description="Clear and descriptive section heading")
    body: str = Field(
        description="In-depth analytical text for this section with inline citations, e.g. [1] or [Source Title]"
    )


class Report(BaseModel):
    """Structured research report produced by the writer."""

    title: str = Field(description="Title of the research report")
    summary: str = Field(description="Executive summary synthesizing the most important insights")
    sections: List[Section] = Field(
        description="Detailed analytical sections comprising the core of the report"
    )
    sources: List[Source] = Field(
        default_factory=list,
        description="List of cited web sources referenced in the report",
    )


class CritiqueItem(BaseModel):
    """Individual critique observation with severity and actionable feedback."""

    category: str = Field(
        description="One of: Missing Information, Unsupported Claim, Structure, Accuracy"
    )
    severity: str = Field(description="Severity level: Low, Medium, or High")
    description: str = Field(description="Precise description of the identified flaw or gap")
    suggestion: str = Field(description="Concrete recommendation on how to address the issue")


class CritiqueReport(BaseModel):
    """Structured evaluation report generated by the critic."""

    missing_info: List[CritiqueItem] = Field(
        default_factory=list,
        description="Critical facts, statistics, or viewpoints absent from the draft",
    )
    unsupported_claims: List[CritiqueItem] = Field(
        default_factory=list,
        description="Statements made without sufficient supporting evidence or citations",
    )
    structure_issues: List[CritiqueItem] = Field(
        default_factory=list,
        description="Issues with logical progression, coherence, or section balance",
    )
    accuracy_concerns: List[CritiqueItem] = Field(
        default_factory=list,
        description="Contradictions, outdated information, or factual ambiguities",
    )
    overall_assessment: str = Field(
        description="Comprehensive summary of the report quality and revision guidance"
    )

    @property
    def all_items(self) -> List[CritiqueItem]:
        """Return a flattened list of all critique items."""
        return (
            self.missing_info
            + self.unsupported_claims
            + self.structure_issues
            + self.accuracy_concerns
        )


class CritiquedReport(BaseModel):
    """Final output bundle containing the revised report and optional critique audit trail."""

    report: Report
    critique: Optional[CritiqueReport] = None

    def to_markdown(self) -> str:
        """Render the complete report into GitHub-flavored markdown."""
        lines = [f"# {self.report.title}\n"]

        lines.append("## Executive Summary\n")
        lines.append(f"{self.report.summary}\n")

        for sec in self.report.sections:
            lines.append(f"## {sec.heading}\n")
            lines.append(f"{sec.body}\n")

        if self.report.sources:
            lines.append("## Sources & References\n")
            for idx, src in enumerate(self.report.sources, start=1):
                title = src.title or src.url
                lines.append(f"{idx}. [{title}]({src.url})")
            lines.append("")

        if self.critique:
            lines.append("---\n")
            lines.append("## Editorial Critique & Review Log\n")
            lines.append(f"**Overall Assessment:** {self.critique.overall_assessment}\n")

            all_critiques = self.critique.all_items
            if all_critiques:
                lines.append("| Category | Severity | Issue | Suggestion |")
                lines.append("| :--- | :--- | :--- | :--- |")
                for c in all_critiques:
                    # Sanitize pipes for markdown table formatting
                    desc = c.description.replace("|", "/")
                    sug = c.suggestion.replace("|", "/")
                    lines.append(f"| {c.category} | {c.severity} | {desc} | {sug} |")
                lines.append("")

        return "\n".join(lines)
