import re

from pydantic import BaseModel, Field


class Source(BaseModel):
    """Web source retrieved during research."""

    url: str
    title: str = ""
    snippet: str = ""


class ResearchPlan(BaseModel):
    """Structured plan and source list generated by the research phase."""

    query: str
    search_queries: list[str] = Field(default_factory=list)
    sources: list[Source] = Field(default_factory=list)


class Extract(BaseModel):
    """Cleaned webpage extract retrieved by the parallel reader."""

    url: str
    title: str = ""
    content: str = ""
    error: str | None = None


class Section(BaseModel):
    """Section within the research report."""

    heading: str
    body: str


class Report(BaseModel):
    """Structured research report produced by the writer."""

    title: str
    summary: str
    sections: list[Section] = Field(default_factory=list)
    diagram: str | None = None
    sources: list[Source] = Field(default_factory=list)


class CritiqueItem(BaseModel):
    """Individual critique observation with severity and actionable feedback."""

    category: str
    severity: str
    description: str
    suggestion: str


class CritiqueReport(BaseModel):
    """Structured evaluation report generated by the critic."""

    items: list[CritiqueItem] = Field(default_factory=list)
    overall_assessment: str = ""


class CritiquedReport(BaseModel):
    """Final output bundle containing the report and optional critique."""

    report: Report
    critique: CritiqueReport | None = None

    def to_markdown(self) -> str:
        """Render the complete report into GitHub-flavored markdown."""
        lines = [
            f"# {self.report.title}\n",
            f"## Executive Summary\n{self.report.summary}\n",
        ]

        if self.report.diagram and self.report.diagram.strip():
            diag = self.report.diagram.strip()
            if not diag.startswith("```"):
                diag = f"```mermaid\n{diag}\n```"
            lines.append(f"## Conceptual Architecture & Visual Flow\n\n{diag}\n")

        for sec in self.report.sections:
            lines.append(f"## {sec.heading}\n{sec.body}\n")

        if self.report.sources:
            lines.append("## Sources & References")
            for idx, src in enumerate(self.report.sources, 1):
                title = src.title or src.url
                lines.append(f"{idx}. [{title}]({src.url})")
            lines.append("")

        if self.critique and self.critique.items:
            lines.append("---\n## Editorial Critique & Review Log")
            lines.append(f"**Overall Assessment:** {self.critique.overall_assessment}\n")
            lines.append("| Category | Severity | Issue | Suggestion |")
            lines.append("| :--- | :--- | :--- | :--- |")
            for c in self.critique.items:
                desc = c.description.replace("|", "/")
                sug = c.suggestion.replace("|", "/")
                lines.append(f"| {c.category} | {c.severity} | {desc} | {sug} |")
            lines.append("")

        return "\n".join(lines)


def parse_json_response(content: str, model_cls: type[BaseModel]) -> BaseModel:
    """Extract and parse JSON into a Pydantic model from raw text or markdown code blocks."""
    text = content.strip()
    match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", text)
    if match:
        text = match.group(1).strip()
    elif (start := text.find("{")) != -1 and (end := text.rfind("}")) > start:
        text = text[start : end + 1]
    return model_cls.model_validate_json(text)
